### ISSUE TITLE
Remember me?

### ISSUE THREAD

**Issue by ghost** [Project-Luxy/HWID_Spoofer#2]
bro I'm plague creator 
do you remember me?

**Comment by Project-Luxy** [comment]
tf

**Comment by Mr-Cuda** [comment]
I'm plague creator
that of EU bot remember?
we created Carbonium and luxyFN together

**Comment by LuxyFN** [comment]
Hi Luxy, it's me, Pablo, or maybe Lince idk. Do you remember me?, chip and wild community? Btw me, you and plague-creator (mr.cuda), were creating a dev called LuciferFN, made in C++ but it was discontinued bc you got a children with your girlfriend. So we continued the dev, and it is currently called LuxyFN, in your honor. Here I have some photo to make you remember.
![img1](https://user-images.githubusercontent.com/100735365/179363146-5c2c140d-7a2b-4483-a124-7458f58a8341.png)
![img2](https://user-images.githubusercontent.com/100735365/179363170-3f06c3cb-7e41-4d6b-b41d-21b1a3f99c2b.png)

**Comment by Project-Luxy** [comment]
plague what a pleasure, of course I remember
oh and wild yeah, great times
well why did you come to my github?

**Comment by Mr-Cuda** [comment]
Well, we wanted to know how things are for you ... Like the baby and how are you. On top of that we have come to ask if you would like to get back into our dev, you know how it is .. epic games has added a new anti cheat and we need someone who can bypass it. Let us know what you think, the choice is free.

**Comment by Project-Luxy** [comment]
The baby is fine and I’m fine, but realize that I don’t even have time to eat 😂
I’m sorry but I haven’t touched a string of code in months 
and I don’t even play fortnite anymore, it would be difficult to bypass that anticheat
oh and plague you finished the bigdrop?

**Comment by LuxyFN** [comment]
Good luxy, I'm happy for you and your family 😊
Btw what is the bigdrop? I'm curious

**Comment by Mr-Cuda** [comment]
bro i didn’t release the bigdrop
I stopped developing it when you left

**Comment by Mr-Cuda** [comment]
there was no reason to continue

**Comment by LuxyFN** [comment]
Plague told me what it is, I said that we can continue it together but he doesn't want..

**Comment by Project-Luxy** [comment]
always the usual lazy

if he did this something bad must have happened 
he was very motivated to create it 😶

**Comment by Mr-Cuda** [comment]
you know that I'm still here right?

**Comment by LuxyFN** [comment]
Idk

**Comment by LuxyFN** [comment]
He quitted luxyfn today 😭

**Comment by Mr-Cuda** [comment]
i'm still here part 2

**Comment by LuxyFN** [comment]
Ye wtf

**Comment by Mr-Cuda** [comment]
ratioooooooooo

**Comment by Project-Luxy** [comment]
plague why did you quit luxyfn

**Comment by Mr-Cuda** [comment]
Cuz shit and I am tired

**Comment by LuxyFN** [comment]
Lmfao

**Comment by Mr-Cuda** [comment]
bro got mad

**Comment by Mr-Cuda** [comment]
can i close now?

**Comment by LuxyFN** [comment]
No ofc

**Comment by Mr-Cuda** [comment]
whywhwywhwywwhwhywyhyhwhywhywyhwyhwyhwyh why
owowowowo
live chat

**Comment by LuxyFN** [comment]
Se* cam

**Comment by Mr-Cuda** [comment]
vuoi fare s*xchat? 
io ci sto

**Comment by LuxyFN** [comment]
Pure io

**Comment by Mr-Cuda** [comment]
da che vuoi iniziare?

**Comment by LuxyFN** [comment]
Una albicocca

**Comment by Mr-Cuda** [comment]
cerco di infilarla nel retto
sarà doloroso

**Comment by Mr-Cuda** [comment]
comunque posso chiudere qua?

**Comment by LuxyFN** [comment]
Nah

**Comment by Project-Luxy** [comment]
wtf

**Comment by Mr-Cuda** [comment]
can i close this issue?

**Comment by LuxyFN** [comment]
Why

**Comment by Mr-Cuda** [comment]
Closed

**Comment by Mr-Cuda** [comment]
yooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo

**Comment by Mr-Cuda** [comment]
@Luxyy-hub 

R. many wishes!
having a child (in my opinion) is the most beautiful thing in the world :)

when I saw that post on insta I immediately thought about making you wishes ... but I preferred to wait.
enjoy your new family , stay with j and have fun!!!!!!!!!!!!!!!!!!

I did not know how to contact you so I am writing to you here

(don't forget I paid you for the new project so hurry up ... just kidding take your time, good evening or day " daddy "

**Comment by LuxyFN** [comment]
> @Luxyy-hub
> 
> R. many wishes! having a child (in my opinion) is the most beautiful thing in the world :)
> 
> when I saw that post on insta I immediately thought about making you wishes ... but I preferred to wait. enjoy your new family , stay with j and have fun!!!!!!!!!!!!!!!!!!
> 
> I did not know how to contact you so I am writing to you here
> 
> (don't forget I paid you for the new project so hurry up ... just kidding take your time, good evening or day " daddy "

new project.. 😭

**Comment by Mr-Cuda** [comment]
@LuxyFN che cosa ti pensi, che sia un nuovo server di fortnite? ☠

**Comment by Mr-Cuda** [comment]
# Auto detect text files and perform LF normalization
* text=auto

**Comment by LuxyFN** [comment]
> @LuxyFN che cosa ti pensi, che sia un nuovo server di fortnite? ☠

Nooo
__we will be releasing v2 in the coming weeks.__

**Comment by Mr-Cuda** [comment]
Piuttosto fai gli auguri al nuovo daddy

**Comment by Mr-Cuda** [comment]
Dai cazzo

**Comment by Mr-Cuda** [comment]
@Luxyy-hub R answer cuz i need help finishing v1 some stuff with v2 and lobbybot matchmaking

I know you are busy but the deadline (especially for the second thing) is coming

**Comment by Luxyy-hub** [comment]
@Mr-Cuda here I am, thank you very much for all wishes, I don't have much time but I can continue, please don't keep writing more from github or messenger I hate it

I can reinstall discord if you want I'm comfortable from there

**Comment by Mr-Cuda** [comment]
Yes reinstall it
Zanzibar#3563

**Comment by Mr-Cuda** [comment]
#3562 sorry
